### ISSUE TITLE
希望可以用自己的有道key

### ISSUE THREAD

**Issue by youthcould** [whklhh/youdao-dic-plugin-for-listary6beta#1]
亲，多谢你的好东东，但我这里现在就不能用了，昨天还好的，希望可以用自己的有道key

**Comment by youthcould** [comment]
update：又好了，不知道为啥，不过如果有个稳定方案就更好了

**Comment by whklhh** [comment]
我看了一下有道注册会送50/100体验金，但是每月会统计量清零，清零的时候不会扣费吗？

**Comment by whklhh** [comment]
已更新

**Comment by youthcould** [comment]
> 我看了一下有道注册会送50/100体验金，但是每月会统计量清零，清零的时候不会扣费吗？

我是送了100体验金，至于你说的清零问题我也不清楚。非常感谢了，fork了备份一个

**Comment by SiFan229** [comment]
大佬，接入方式是API吗
