### ISSUE TITLE
现在还能用吗？

### ISSUE THREAD

**Issue by kiphu** [whklhh/youdao-dic-plugin-for-listary6beta#2]
用官方接口那个，listary,进入翻译状态后输入任意字符就看到右边那个圈一直转个不停,但就是不返回翻译结果。

**Comment by whklhh** [comment]
我自用也是比较随缘=。=有时可以有时不行，调试的时候直接调js会有点慢，但是通了以后再用listary访问就成功了；
你可以直接用node执行js调试看看

**Comment by kiphu** [comment]
能用了，多谢
